### ISSUE TITLE
Nice re-design, mobile problems.

### ISSUE THREAD

**Issue by radman-x** [lo-th/Ammo.lab#6]
Nice re-design a few weeks ago, this is a big improvement of both libs. However, there seem to be some problems with running some of the demos (eg, asteriod) on a mobile device. We are getting missing textures, shader problems, etc. on some of the demos running on a Samsung S8. Have you tried the demos on a mobile phone?

**Comment by radman-x** [comment]
One other point, the older version demos ran fine on the same mobile device.

**Comment by lo-th** [comment]
hum yes i try on S8 without problem's maybe your cache not refreshed ?
i have to improve mobile support i use new material ( lambert vs standard )
is pretty heavy for phone and also last dev version of three not complete.

**Comment by radman-x** [comment]
Cleared cache and still not working (see asterioid attached). Strange that it runs on your S8...
![1551717599664](https://user-images.githubusercontent.com/9258904/53748164-68f73e00-3e6a-11e9-8bf9-a5f78f52c4d1.jpg)

**Comment by lo-th** [comment]
what mobile ? browser ?

**Comment by radman-x** [comment]
Samsung Galaxy S8 (model SM-G955U1)
Android 8.0.0, Build/R16NW
Chrome 72.0.3626.105

**Comment by lo-th** [comment]
ha ok strange ? i have same version and model 
( maybe is a american phone me is european not the same proc )
anyway i while update soon with some mobile optimisation  
low background and environement.

**Comment by radman-x** [comment]
OK, if I get a chance, will try to run remotely in debugger and see if any error shows up in the console. Also, in looking through the code a bit, I see that the material on the asteroid was changed from phong to standard, I may try changing it back and see what happens.

**Comment by lo-th** [comment]
yes maybe i change for phong on mobile, i have to try but standard is realy good
i make a update on lab (lower cube map reflection)

**Comment by radman-x** [comment]
Another important piece of info: another member of our dev team ran the demos on his Samsung S7 and they seem to run fine! This seems to be something unique to my phone. It might be good to either wait for a few days until I can do the debugging above or, maybe, have some type of option in the AmmoLab configuration options like "basicMobile" that users can change. Like you said, it is nicer to have the standard material than the phong material and it appears that many phones can handle that.

**Comment by radman-x** [comment]
After upgrading to Android 9, the current version of Ammo.lab now works fiine. So am closing this issue. Thanx for your prompt respo see.

**Comment by radman-x** [comment]
Hi loth - I sent you an email a week or so ago and didn't hear back. Did
you get it?

Bruce
