### ISSUE TITLE
How to simply introduce the necessary files

### ISSUE THREAD

**Issue by WREQI** [lo-th/Ammo.lab#8]
I want to use your engine, please introduce the few files to use, your code is too much, I look complicated

**Comment by WREQI** [comment]
![image](https://user-images.githubusercontent.com/35467304/61182442-b039da80-a665-11e9-95a4-5a4232a36a3f.png)
I saw your view from lab.js. How do I use ammo.lab separately to use it?Which documents are necessary?

**Comment by WREQI** [comment]
I saw an index_test.html file, which only uses the shot.js file. Only this is a must.

**Comment by lo-th** [comment]
Yes you only need with index_test.html in build 
shot.js // the worker with three stuff for 3d view
gun.js // is ammo side 
ammo.hex // is the compress version of ammo.js
and for sure three.js

for full option you need lab.js https://github.com/lo-th/lab
i'm on big update for easy use without more external files .

**Comment by WREQI** [comment]
okay

**Comment by lirilC** [comment]
Hey!, lo-th, what's up? I was wondering the same... I think. I made a project using the lab, and would like to use index_test.html, let's say... I use things like view.load(...) and other things that appear to not be functions in index_test.html. I really like Ammo.lab so would prefer to not switch to Phy. I was wondering, what would I have to do to have the same functionalities on index_test.html as in the Ammo.lab. Thank you very much!!! tl;dr: how can I have my Ammo.lab-made project working with no lab.
