### ISSUE TITLE
Ask you a question

### ISSUE THREAD

**Issue by WREQI** [lo-th/Ammo.lab#9]

**Comment by WREQI** [comment]
I also considered physically implementing adsorption and other functions.

**Comment by wenrenqiang** [comment]
image
I saw that you have multiple rays and physical moving objects. There is no jamming. I am going to modify the added ray moving object directly in the three editors.

**Comment by WREQI** [comment]
![image](https://user-images.githubusercontent.com/35467304/61573551-60369a00-aae3-11e9-9a66-54a71e9c9f2a.png)
I saw that other people use physical plus ray to move without card. I am modifying the added ray in the three editors.

**Comment by lo-th** [comment]
i don't understand , now i fixe physics ray 
ray can be add to aniy object and return distance 

example 
var frontRay = physic.add({ type:'ray',name:'frontRay', parent:base,  pos:[31.8,1,0], start:[0,0,0], end:[300,0,0], mask:1, precision:1 });

ray alway return info 
frontRay.info = { hit:true, distance;100, name:'name ofhitobject', point:[10,2,0] , normal:[]0,1,0}
